config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  
  get '/' => 'home#index', as: :home
  
  get 'elections' => 'election#index', as: :election_list
  get 'elections/:election' => 'election#show', as: :election_show
  get 'elections/:election/candidate-results' => 'election#candidate_results', as: :election_candidate_results
  
  get 'general-elections' => 'general_election#index', as: :general_election_list
  get 'general-elections/:general_election' => 'general_election#show', as: :general_election_show
  
  get 'general-elections/:general_election/candidacies' => 'general_election_candidacy#index', as: :general_election_candidacy_list
  
  get 'general-elections/:general_election/elections' => 'general_election_election#index', as: :general_election_election_list
  
  get 'general-elections/:general_election/constituency-areas' => 'general_election_constituency_area#index', as: :general_election_constituency_area_list
  
  get 'general-elections/:general_election/map' => 'general_election_map#index', as: :general_election_map
  
  get 'general-elections/:general_election/majority' => 'general_election_majority#index', as: :general_election_majority_list
  
  get 'general-elections/:general_election/vote-share' => 'general_election_vote_share#index', as: :general_election_vote_share_list
  
  get 'general-elections/:general_election/turnout' => 'general_election_turnout#index', as: :general_election_turnout_list
  
  get 'general-elections/:general_election/declaration-times' => 'general_election_declaration_times#index', as: :general_election_declaration_time_list
  
  get 'general-elections/:general_election/political-parties' => 'general_election_party#index', as: :general_election_party_list
  get 'general-elections/:general_election/political-parties/:political_party' => 'general_election_party#show', as: :general_election_party_show
  
  get 'general-elections/:general_election/political-parties/:political_party/elections' => 'general_election_party_election#index', as: :general_election_party_election_list
  get 'general-elections/:general_election/political-parties/:political_party/elections/won' => 'general_election_party_election#won', as: :general_election_party_election_won
  
  get 'general-elections/:general_election/uncertified-candidacies' => 'general_election_uncertified_candidacy#index', as: :general_election_uncertified_candidacy_list
  
  get 'general-elections/:general_election/boundary-sets' => 'general_election_boundary_set#index', as: :general_election_boundary_set_list
  
  
  get 'general-elections/:general_election/countries' => 'general_election_country#index', as: :general_election_country_list
  get 'general-elections/:general_election/countries/:country' => 'general_election_country#show', as: :general_election_country_show
  
  get 'general-elections/:general_election/countries/:country/candidacies' => 'general_election_country_candidacy#index', as: :general_election_country_candidacy_list
  
  get 'general-elections/:general_election/countries/:country/elections' => 'general_election_country_election#index', as: :general_election_country_election_list
  
  get 'general-elections/:general_election/countries/:country/constituency-areas' => 'general_election_country_constituency_area#index', as: :general_election_country_constituency_area_list
  
  get 'general-elections/:general_election/countries/:country/majority' => 'general_election_country_majority#index', as: :general_election_country_majority_list
  
  get 'general-elections/:general_election/countries/:country/vote-share' => 'general_election_country_vote_share#index', as: :general_election_country_vote_share_list
  
  get 'general-elections/:general_election/countries/:country/turnout' => 'general_election_country_turnout#index', as: :general_election_country_turnout_list
  
  get 'general-elections/:general_election/countries/:country/declaration-times' => 'general_election_country_declaration_time#index', as: :general_election_country_declaration_time_list
  
  get 'general-elections/:general_election/countries/:country/political-parties' => 'general_election_country_political_party#index', as: :general_election_country_political_party_list
  get 'general-elections/:general_election/countries/:country/political-parties/:political_party' => 'general_election_country_political_party#show', as: :general_election_country_political_party_show
  
  get 'general-elections/:general_election/countries/:country/political-parties/:political_party/elections' => 'general_election_country_party_election#index', as: :general_election_country_party_election_list
  get 'general-elections/:general_election/countries/:country/political-parties/:political_party/elections/won' => 'general_election_country_party_election#won', as: :general_election_country_party_election_won
  
  get 'general-elections/:general_election/countries/:country/uncertified-candidacies' => 'general_election_country_uncertified_candidacy#index', as: :general_election_country_uncertified_candidacy_list
  
  
  get 'general-elections/:general_election/countries/:country/english-regions' => 'general_election_english_region#index', as: :general_election_english_region_list
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region' => 'general_election_english_region#show', as: :general_election_english_region_show
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/candidacies' => 'general_election_english_region_candidacy#index', as: :general_election_english_region_candidacy_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/constituency-areas' => 'general_election_english_region_constituency_area#index', as: :general_election_english_region_constituency_area_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/majority' => 'general_election_english_region_majority#index', as: :general_election_english_region_majority_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/vote-share' => 'general_election_english_region_vote_share#index', as: :general_election_english_region_vote_share_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/turnout' => 'general_election_english_region_turnout#index', as: :general_election_english_region_turnout_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/declaration-times' => 'general_election_english_region_declaration_time#index', as: :general_election_english_region_declaration_time_list
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/political-parties' => 'general_election_english_region_political_party#index', as: :general_election_english_region_political_party_list
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/political-parties/:political_party' => 'general_election_english_region_political_party#show', as: :general_election_english_region_political_party_show
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/political-parties/:political_party/elections' => 'general_election_english_region_party_election#index', as: :general_election_english_region_party_election_list
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/political-parties/:political_party/elections/won' => 'general_election_english_region_party_election#won', as: :general_election_english_region_party_election_won
  
  get 'general-elections/:general_election/countries/:country/english-regions/:english_region/uncertified-candidacies' => 'general_election_english_region_uncertified_candidacy#index', as: :general_election_english_region_uncertified_candidacy_list
  
  get 'constituency-areas' => 'constituency_area#index', as: :constituency_area_list
  get 'constituency-areas/current' => 'constituency_area#current', as: :constituency_area_list_current
  get 'constituency-areas/all' => 'constituency_area#all', as: :constituency_area_list_all
  get 'constituency-areas/:constituency_area' => 'constituency_area#show', as: :constituency_area_show
  
  get 'constituency-areas/:constituency_area/elections' => 'constituency_area_election#index', as: :constituency_area_election_list
  
  get 'constituency-areas/:constituency_area/maiden-speeches' => 'constituency_area_maiden_speech#index', as: :constituency_area_maiden_speech_list
  
  get 'constituency-areas/:constituency_area/overlaps' => 'constituency_area_overlap#show', as: :constituency_area_overlap_show
  
  get 'constituency-area-overlaps' => 'constituency_area_overlap#index', as: :constituency_area_overlap_list
  
  get 'constituency-areas/current/countries' => 'constituency_area_country#index', as: :constituency_area_country_list
  get 'constituency-areas/current/countries/:country' => 'constituency_area_country#show', as: :constituency_area_country_show
  
  get 'constituency-areas/current/countries/:country/english-regions' => 'constituency_area_english_region#index', as: :constituency_area_english_region_index
  get 'constituency-areas/current/countries/:country/english-regions/:english_region' => 'constituency_area_english_region#show', as: :constituency_area_english_region_show
  
  get 'political-parties' => 'political_party#index', as: :political_party_list
  get 'political-parties/winning' => 'political_party#winning', as: :political_party_winning_list
  get 'political-parties/fall' => 'political_party#fall', as: :political_party_fall
  get 'political-parties/:political_party' => 'political_party#show', as: :political_party_show
  

app/controllers/general_election_country_constituency_area_controller.rb
class GeneralElectionCountryConstituencyAreaController < ApplicationController
  
  def index
    country = params[:country]
    @country = Country.find( country )
    @countries = @general_election.child_countries_with_elections_in_country( @country )
    @english_regions = @general_election.english_regions_in_country( @country )
    @elections = @general_election.elections_in_country_without_electorate( @country)
    
    @page_title = "#{@general_election.common_title} - #{@country.name} - by constituency"
    @multiline_page_title = "#{@general_election.common_title} <span class='subhead'>#{@country.name} - by constituency</span>".html_safe
    @description = "#{@general_election.common_description} in #{@country.name}, listed by constituency."
    @crumb << { label: 'Parliament periods', url: parliament_period_list_url }
    @crumb << { label: @general_election.parliament_period_crumb_label, url: parliament_period_show_url( :parliament_period => @general_election.parliament_period_number) }
    @crumb << { label: @general_election.crumb_label, url: general_election_show_url }
    @crumb << { label: @country.name, url: general_election_country_show_url }
    @crumb << { label: 'Constituencies', url: nil }
    @section = 'elections'
    @subsection = 'constituency-areas'
    render :template => 'general_election_country_constituency_area/index_notional' if @general_election.is_notional
  end
end

app/views/general_election_country_constituency_area/_previous_next.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 text-start"><%= content_tag( 'span', link_to( 'Previous general election', general_election_country_constituency_area_list_url( :general_election => previous_next.previous_general_election ), :rel => 'prev' ), :class => 'previous' ) if previous_next.previous_general_election %>
		</div>
		<div class="col-6 text-end"><%= content_tag( 'span', link_to( 'Next general election', general_election_country_constituency_area_list_url( :general_election => previous_next.next_general_election ), :rel => 'next' ), :class => 'next' ) if previous_next.next_general_election %>
		</div>
	</div>
</div>

app/views/general_election_country_constituency_area/index.html.erb
<%= render :partial => 'previous_next', :object => @general_election %>

<%= render :partial => 'general_election_country/nav' %>

<%= render :partial => 'general_election/counts', :object => @general_election %>

<% if @country.geographic_code -%>
	<% if @country.ons_linked -%>
		<%= content_tag( 'p', "Geographic code: #{link_to( @country.geographic_code, "https://www.ons.gov.uk/visualisations/areas/#{@country.geographic_code}/" )}".html_safe ) %>
	<% else -%>
		<%= content_tag( 'p', "Geographic code: #{@country.geographic_code}" ) %>
	<% end -%>
<% end -%>

<% unless @countries.empty? %>
	<div id="countries">
		<%= content_tag( 'h2', "Countries in #{@country.name}" ) %>
		<ol>
			<%= render :partial => 'general_election_country/country', :collection => @countries %>
		</ol>
	</div>
<% end -%>

<% unless @english_regions.empty? %>
	<div id="english-regions">
		<%= content_tag( 'h2', 'English regions' ) %>
		<ol>
			<%= render :partial => 'general_election_english_region/english_region', :collection => @english_regions %>
		</ol>
	</div>
<% end -%>

<% unless @elections.empty? %>
	<div id="elections-<%= @country.name.downcase %>">
		<%= content_tag( 'h2', "Elections in #{@country.name}" ) %>
		<ol>
			<%= render :partial => 'election/election', :collection => @elections %>
		</ol>
	</div>
<% end -%>

<% unless @elections.empty? %>
	<div id="downloads">
		<p>
			<%= csv_icon_link(	general_election_country_candidacy_list_url( :format => 'csv' ), "Download the full data set: candidate-level general election result data in #{@country.name} as a CSV file." ) %>
		</p>
	</div>
<% end -%>

app/views/general_election_country_constituency_area/index_notional.html.erb
<%= render :partial => 'general_election/counts', :object => @general_election %>

<%= render :partial => 'general_election_country/nav' %>

<% if @country.geographic_code -%>
	<% if @country.ons_linked -%>
		<%= content_tag( 'p', "Geographic code: #{link_to( @country.geographic_code, "https://www.ons.gov.uk/visualisations/areas/#{@country.geographic_code}/" )}".html_safe ) %>
	<% else -%>
		<%= content_tag( 'p', "Geographic code: #{@country.geographic_code}" ) %>
	<% end -%>
<% end -%>

<% unless @countries.empty? %>
	<div id="countries">
		<%= content_tag( 'h2', "Countries in #{@country.name}" ) %>
		<%= content_tag( 'p', "Countries having notional results for the #{@general_election.polling_on.year} general election." ) %>
		<ol>
			<%= render :partial => 'general_election_country/country', :collection => @countries %>
		</ol>
	</div>
<% end -%>

<% unless @english_regions.empty? %>
	<div id="english-regions">
		<%= content_tag( 'h2', 'English regions' ) %>
		<ol>
			<%= render :partial => 'general_election_english_region/english_region', :collection => @english_regions %>
		</ol>
	</div>
<% end -%>

<% unless @elections.empty? %>
	<div id="elections-<%= @country.name.downcase %>">
		<%= content_tag( 'h2', "Notional election results in #{@country.name}" ) %>
		<ol>
			<%= render :partial => 'election/election', :collection => @elections %>
		</ol>
	</div>
<% end -%>

<%= render :partial => 'notional/notice' %>

<% unless @elections.empty? %>
	<div id="downloads">
		<p>
			<%= csv_icon_link(	general_election_country_candidacy_list_url( :format => 'csv' ), "Download the full data set: candidate-level general election result data in #{@country.name} as a CSV file." ) %>
		</p>
	</div>
<% end -%>